### ISSUE TITLE
Unable to install in 2.79

### ISSUE THREAD

**Issue by samfromnewzealand** [ScottishCyclops/tensionmap#1]
Thanks so much for picking up development on this awesome add on. Blender 2.79 is telling me it's installed the addon but refreshing the list or restarting program doesn't allow it to appear in the addon list. Any help would be appreciated!

**Comment by samfromnewzealand** [comment]
Update: I was able to install the ZIP from BlenderArtists

**Comment by ScottishCyclops** [comment]
As it turns out, Blender ignores addon folders with `.` or `-` and Github automatically names the folder inside the ZIP with the version name.

I've made a new release (1.0.1.1) with a manually created ZIP attached, and it now works. It is not a problem with the code at all.

Thanks for pointing this out, I'm marking the issue resolved. Please open a new one in case of more problems.

Scott
