### ISSUE TITLE
Creation of Tension Map

### ISSUE THREAD

**Issue by SheepDomination** [ScottishCyclops/tensionmap#5]
What is the foundation of a tension map ? I'm trying to find papers on how a tension map is created ?

**Comment by ScottishCyclops** [comment]
Hey,

I don't think this addon was implemented from a paper. I can't know for sure because it's a rewrite of an older addon.
I had to fully understand it, but I didn't come up with the logic.

Let me explain the way it works.

The "tension" is computed for each edge.
To find the tension, we look at the edge length in blender units when no modifiers are applied to it (that includes most importantly the "Armature" modifier), and then the edge length with the modifiers applied to it.

Taking the difference between the original edge length and the modified edge length gives us the tension.
We then accumulate that difference on the two vertices that form the edge, because every vertex could be part of more than one edge.

When all edges have been calculated, for each vertex, if the value is negative, we know it has been squeezed. If the value is positive, it has been stretched.

The logic that I just explained should be easily visible in the code, even if you are not very familiar with it.
Is it well commented too, and I recommend you give it a look if you are interested in the details !

Let me know if you have any other questions.

Scott
